import heroImg from "../assets/blog/maps-lead-engine-hero.png";
import enrichImg from "../assets/blog/maps-lead-engine-enrich.png";
import outreachImg from "../assets/blog/maps-lead-engine-outreach.png";

export type Block =
  | { t: "p"; text: string }
  | { t: "h2"; text: string }
  | { t: "quote"; text: string; by?: string }
  | { t: "list"; items: string[] }
  | { t: "image"; src: string; alt: string; caption: string }
  | { t: "stat"; stat: string; label: string }
  | { t: "callout"; title: string; text: string };

export interface Post {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  readMins: number;
  author: { name: string; role: string; initials: string };
  keywords: string[];
  hero: string | null;
  coverIcon: "map" | "shield" | "mail";
  content: Block[];
}

export const POSTS: Post[] = [
  {
    slug: "google-maps-lead-generation-guide",
    title: "How to Turn Google Maps Into a Predictable Lead-Gen Machine (2026 Guide)",
    excerpt:
      "Google Maps is the largest, freshest database of local businesses on earth — and almost nobody uses it systematically for outbound. Here's the exact five-step system agencies and sales teams use to turn map searches into meetings.",
    category: "Playbooks",
    date: "Feb 12, 2026",
    readMins: 11,
    author: { name: "Dev Patel", role: "Growth @ zybble", initials: "DP" },
    keywords: ["google maps lead generation", "google maps leads", "local business leads", "scrape google maps", "b2b prospecting", "lead lists"],
    hero: heroImg,
    coverIcon: "map",
    content: [
      {
        t: "p",
        text: "Every week, agency owners and sales leaders ask us the same question: \"Where do you actually find good local business leads?\" The honest answer is hiding in plain sight. Google Maps holds more than 200 million business listings worldwide, updated daily by the businesses themselves — their categories, phone numbers, websites, opening hours, and unfiltered customer reviews. It is the largest, freshest, most self-maintained B2B database on the planet. And yet most teams still buy stale lists from data warehouses that were compiled eighteen months ago.",
      },
      {
        t: "p",
        text: "This guide lays out the exact five-step system that over 2,300 zybble customers use to turn Google Maps lead generation from a manual grind into a predictable pipeline machine. It works whether you're a two-person agency hunting dentists in Dallas or a forty-rep sales org carving up the entire Midwest. No scripts, no proxies, no CSV archaeology required.",
      },
      {
        t: "stat",
        stat: "41M",
        label: "verified local-business leads generated by zybble teams last quarter alone",
      },
      { t: "image", src: heroImg, alt: "Isometric illustration of a dark city map with glowing lime location pins representing Google Maps leads", caption: "Google Maps is a living database of 200M+ businesses — maintained daily by the owners themselves." },
      { t: "h2", text: "Step 1: Define your ICP in map language" },
      {
        t: "p",
        text: "The biggest mistake in Google Maps lead generation is searching like a human instead of like a machine. Humans type \"dentists near me.\" Machines want structure: niche × geography. Before you touch a tool, write down your ideal customer profile in three parts: the category (\"orthodontists\", not \"healthcare\"), the territory (\"greater Phoenix\", not \"Arizona\"), and the disqualifiers (chains, franchises, businesses with fewer than 10 reviews). The tighter the definition, the higher your reply rates downstream. Agencies running this play typically maintain 5–10 active niche definitions and rotate them weekly to keep lists fresh.",
      },
      {
        t: "list",
        items: [
          "Category: pick the exact Maps category your buyers use — \"med spa\" and \"day spa\" are different lists with different economics.",
          "Territory: cities beat states. \"Roofers · Denver + Aurora + Boulder\" outperforms \"roofers · Colorado\" every time.",
          "Qualifiers: review count (10–500 is the sweet spot for owner-operated), rating (3.8+ signals a healthy business), and recency of reviews.",
          "Volume math: 1,000 verified leads ÷ 9% reply rate ÷ 30% meeting rate ≈ 27 conversations. Size your territory accordingly.",
        ],
      },
      { t: "h2", text: "Step 2: Search at scale — chain, don't dabble" },
      {
        t: "p",
        text: "A single Maps search returns a few dozen results before pagination gets hostile. Serious Google Maps scraping means chaining: automatically expanding your query across every neighborhood, ZIP code, and suburb in your territory, then deduplicating the results into one canonical list. This is exactly the part that used to require Python scripts, rotating proxies, and a prayer. Today it's one input field. With zybble you type \"roofers · Denver, CO\", queue sixteen surrounding cities behind it, and watch a few thousand structured records stream in — name, address, category, rating, review count, hours, website — with franchises and duplicates already stripped out.",
      },
      {
        t: "quote",
        text: "List building used to eat a full day of my week. Now I queue three niche chains on Monday morning and the CSVs are waiting before my coffee is cold.",
        by: "Sofia Marino, Partner · Marino & Vale",
      },
      { t: "h2", text: "Step 3: Enrich and verify before you spend a single send" },
      {
        t: "image", src: enrichImg, alt: "Isometric illustration of a map pin connected to enriched contact cards, email and phone icons, and verification badges", caption: "Enrichment: every listing is matched with verified emails, direct dials, and a confidence score before it costs a credit." },
      {
        t: "p",
        text: "A business listing alone doesn't book meetings — a verified contact does. This is where most Google Maps lead scraping pipelines quietly fail: they hand you generic info@ addresses and front-desk numbers scraped years ago, and your sender reputation pays the price. The non-negotiable pipeline looks like this: match each business to real contacts from licensed B2B sources, run every email through live SMTP and pattern verification, line-type check every phone number (mobile versus landline changes your entire call strategy), and confidence-score the record. Anything that fails gets quarantined, not exported.",
      },
      {
        t: "callout",
        title: "The 30-day decay rule",
        text: "B2B contact data decays at roughly 2–3% per month — people quit, businesses close, mailboxes die. A list verified in January is a different list by March. Always verify at export time, and always demand automatic refunds for hard bounces. If your provider won't refund bounces, they're telling you something about their data.",
      },
      { t: "h2", text: "Step 4: Outreach that references the map (this is the multiplier)" },
      {
        t: "p",
        text: "Here's the part almost everyone skips, and it's the highest-leverage move in this entire system. You don't just know a business exists — you know their rating, their review count, what customers praised last Tuesday, and how long they've been open. Generic cold email patterns (\"Hope this finds you well…\") actively waste that advantage. Modern AI assistants can read each business's reviews and write openers that reference them specifically: the recurring compliments, the service gaps reviewers mention, even the owner's name from review responses. Across zybble campaigns, review-aware openers lift reply rates from the 2–3% industry baseline to 8–9%, because the email reads like you did twenty minutes of homework — except it took twenty milliseconds.",
      },
      {
        t: "image", src: outreachImg, alt: "Isometric illustration of glowing envelopes flying from a laptop toward map pins, representing AI-personalized outreach to local businesses", caption: "Review-aware AI openers lift reply rates from ~2.5% to 8–9% because they read like homework, not automation."
      },
      {
        t: "list",
        items: [
          "Lead with a specific observation: their rating, a recent review theme, a milestone (\"congrats on the second location\").",
          "Bridge to their economics, not your features: more booked inspections, fuller tables, back-to-back Thursdays.",
          "One low-friction ask: a 12-minute audit call, a free sample analysis, a one-question reply. Never a calendar dump.",
          "Follow up twice with new information each time — a quick win, a relevant case study, a different angle. Then stop.",
        ],
      },
      { t: "h2", text: "Step 5: Measure the machine, then widen it" },
      {
        t: "p",
        text: "Once one niche-city combo works, the system scales horizontally. Track four numbers per combo: verify rate (data quality), reply rate (message quality), positive-reply rate (offer quality), and meetings booked (the only one your CFO cares about). Kill combos below 4% reply rate after 1,000 sends; double down on anything above 8%. Teams running this loop typically stabilize at 3–5 active territories per rep, refreshing each on a 45-day cycle — the point where new businesses, closed businesses, and changed numbers have made the list meaningfully different.",
      },
      { t: "h2", text: "Common mistakes that kill Google Maps lead campaigns" },
      {
        t: "list",
        items: [
          "Exporting without verifying — a single 8% bounce campaign can burn a domain for months.",
          "Pitching franchises as if they were owner-operated; filter them out at search time.",
          "Sending the same opener to a 4.9★ business and a 3.2★ business — the map already told you who needs what.",
          "Giving up after one email; 55–60% of positive replies arrive in follow-ups one and two.",
          "Hoarding every list forever instead of re-verifying on a rolling cycle.",
        ],
      },
      {
        t: "p",
        text: "The map isn't a hack or a loophole — it's infrastructure. The businesses are already there, publicly asking to be found. The only question is whether you find them with a system, or keep paying for lists everyone else has already burned through. Start your first sweep today: your first 500 leads are free, and the whole pipeline above — search, enrich, verify, AI outreach — is included from the $19 plan up.",
      },
    ],
  },
  {
    slug: "ethical-google-maps-data-extraction-compliance",
    title: "The Compliant Guide to Google Maps Data Extraction: GDPR, CAN-SPAM & Common Sense",
    excerpt:
      "Is extracting business data from Google Maps legal? Short answer: yes, when done right. Here's the complete compliance framework — GDPR lawful bases, CAN-SPAM requirements, data minimization, and the operational habits that keep B2B outreach both effective and lawful.",
    category: "Compliance",
    date: "Jan 28, 2026",
    readMins: 9,
    author: { name: "Marie Laurent", role: "Compliance & Legal @ zybble", initials: "ML" },
    keywords: ["google maps scraping legal", "gdpr cold email", "can-spam compliance", "b2b data privacy", "ethical lead generation"],
    hero: null,
    coverIcon: "shield",
    content: [
      {
        t: "p",
        text: "Whenever we demo Google Maps lead extraction to a new customer, the first question isn't about features — it's \"is this legal?\" It's the right question, and the honest answer is nuanced: extracting and using business contact data is lawful in most jurisdictions, provided you respect a clear set of rules about whose data you process, why, and how you contact them. This guide is the same framework our legal team applies internally, written for operators rather than lawyers. It is not legal advice, but it will make your conversations with actual counsel dramatically more productive.",
      },
      { t: "h2", text: "First principle: public business data ≠ personal data (mostly)" },
      {
        t: "p",
        text: "There's a crucial line between a business listing (\"Riverside Dental, 512-555-0148, open 9–5\") and personal data (\"Dr. Priya Raman, lives at…, personal cell…\"). Google Maps listings are published by businesses precisely so the public can find and contact them — that's the entire point of a listing. Processing that business-level data is low-risk almost everywhere. The moment you enrich a listing with an individual's name and direct contact details, however, GDPR-class laws apply, because you've started processing personal data. That doesn't make it illegal — it makes it regulated. Regulation is manageable when you build for it.",
      },
      {
        t: "callout",
        title: "The one-sentence rule",
        text: "Contact businesses about their business, using data relevant to their business — and stop the instant they ask you to.",
      },
      { t: "h2", text: "GDPR: your lawful basis is legitimate interest — if you do the work" },
      {
        t: "p",
        text: "Under GDPR, B2B cold outreach typically relies on the \"legitimate interest\" basis (Article 6(1)(f)). Regulators (notably the UK's ICO) have repeatedly confirmed this can be valid for carefully targeted B2B marketing. But legitimate interest is not a magic word — it's a balance you must actually strike and document in a Legitimate Interest Assessment (LIA). That means your outreach must be relevant to the recipient's professional role (pitching payroll software to a payroll manager: yes; pitching anything to a random employee: no), the data must be proportionate (name, role, business email: yes; home address, personal mobile for non-owners: no), and the recipient must be able to object effortlessly.",
      },
      {
        t: "list",
        items: [
          "Document your LIA: purpose, necessity, and balancing test. One page is enough — but write it down.",
          "Data minimization: export the fields you need for the campaign, nothing more. Hoarding is liability.",
          "Identify yourself truthfully: real name, real company, real physical address in every email.",
          "Honor objections instantly and suppress globally — one \"stop\" ends everything, everywhere.",
          "Keep records re-verified on a rolling cycle; accuracy is a GDPR principle (Article 5), not a nicety.",
          "Have a DPA ready with every processor in your chain — including your lead-data provider.",
        ],
      },
      { t: "h2", text: "CAN-SPAM & friends: the rules of the actual send" },
      {
        t: "p",
        text: "In the US, CAN-SPAM is refreshingly pragmatic: B2B cold email is legal, full stop, as long as you follow the behavioral rules. No deceptive subject lines (a \"Re:\" on a first touch is asking for trouble), no false header information, a valid physical postal address in the footer, a working unsubscribe mechanism honored within ten business days (do it in ten seconds instead), and honest identification of who you are. California's CCPA adds disclosure and deletion rights for state residents; CASL in Canada is stricter and generally requires implied consent — treat Canadian prospects with extra care, using existing-business-relationship or conspicuous-publication provisions where they genuinely apply.",
      },
      {
        t: "stat",
        stat: "10 sec",
        label: "how fast zybble processes an unsubscribe across every campaign — the law gives you 10 days",
      },
      { t: "h2", text: "The technical layer most guides ignore" },
      {
        t: "p",
        text: "Compliance isn't only legal text — it's deliverability hygiene with legal consequences. High bounce rates from unverified data make you look like a scraper-and-spammer to mailbox providers, and spam-folder placement is the practical death penalty for your domain regardless of what's lawful. Keep hard bounces under 2% by verifying every address at export time, authenticate every sending domain with SPF, DKIM and DMARC, ramp new domains slowly (warm-up is boring and non-negotiable), and never scrape behind logins or circumvent technical barriers — accessible public listings only, at respectful crawl rates. zybble enforces exactly these constraints infrastructure-side, which is why our customers' bounce rates average 1.9%.",
      },
      { t: "h2", text: "A pre-flight compliance checklist for every campaign" },
      {
        t: "list",
        items: [
          "Is every recipient plausibly interested in this offer because of their professional role? If not, cut them.",
          "Is the data proportional — business name, role, business email/phone? Strip everything else.",
          "Does the email identify you, your company, and your physical address? Check the template, not your memory.",
          "Is the unsubscribe one click, instant, and honored across all campaigns? Test it monthly.",
          "Are bounce and complaint rates under control (under 2% / under 0.1%)? Pause and fix before sending more.",
          "Is your LIA documented, your DPA signed with each processor, and your list freshly verified? File it.",
        ],
      },
      {
        t: "p",
        text: "None of this is red tape for its own sake. Teams that comply properly also win commercially: relevant, honest, well-targeted outreach gets replies; lazy, broad, deceptive outreach gets reported. Compliance is a quality bar, and quality bars are competitive advantages. Build your Google Maps pipeline on verified public data, contact people like a professional, honor every opt-out instantly — and you can operate with confidence in the US, EU and UK alike.",
      },
      {
        t: "quote",
        text: "Legitimate interest is not a loophole. It's a promise you make to the recipient: this message is worth your professional attention. Keep the promise or don't send the email.",
        by: "Marie Laurent, Compliance & Legal @ zybble",
      },
    ],
  },
  {
    slug: "cold-email-templates-local-businesses",
    title: "9 Cold Email Templates for Local Businesses That Actually Get Replies",
    excerpt:
      "Local business owners delete templated cold email in seconds — but they reply to messages that prove you looked at their business. Nine field-tested templates (roofers, dentists, agencies, recruiters) with the psychology behind each, plus the follow-up math that doubles replies.",
    category: "Outreach",
    date: "Jan 9, 2026",
    readMins: 10,
    author: { name: "Dev Patel", role: "Growth @ zybble", initials: "DP" },
    keywords: ["cold email templates", "cold email local business", "outreach templates", "lead generation email", "b2b cold email"],
    hero: null,
    coverIcon: "mail",
    content: [
      {
        t: "p",
        text: "Local business owners are the hardest cold-email audience on earth. They're busy, they're skeptical, they've been burned by \"marketing agencies\" before, and they're reading your email between customers on a phone with a cracked screen. They also buy — enthusiastically — when an email proves two things in under ten seconds: that you actually looked at their specific business, and that replying costs them almost nothing. These nine templates come from analyzing millions of sends across zybble campaigns. Each one names the mechanism it exploits, so you can adapt it rather than cargo-cult it. Replace anything in [brackets], and let your AI assistant fill the map-specific details per business.",
      },
      { t: "h2", text: "1. The review mirror" },
      {
        t: "quote",
        text: "Subject: that 4.9★ didn't happen by accident · Hi Dana — 212 reviews at 4.9★ for Peak Roofing is rare in Denver; I went through them and the phrase \"showed up when they said they would\" appears over and over. We help roofers turn exactly that reputation into booked inspections — 14 in the last 60 days for a similar crew in Aurora. Worth a 12-minute call this week?",
        by: "Mechanism: specific public proof. Their own customers wrote your opener for you.",
      },
      { t: "h2", text: "2. The gap analysis" },
      {
        t: "quote",
        text: "Subject: Maple Dental vs. BrightSmile (2 streets away) · Hi Dr. Patel — BrightSmile two streets over has 89 reviews and online booking; Maple has 212 reviews and a phone number that goes to voicemail after 4pm. You're winning on reputation and losing on friction. I recorded a 3-minute video showing the exact gap and the fix. Want the link?",
        by: "Mechanism: competitive tension + a micro-ask (a link, not a meeting).",
      },
      { t: "h2", text: "3. The new-in-town welcome" },
      {
        t: "quote",
        text: "Subject: saw you just opened on 5th — congrats · Hi Marco — noticed Casa Verde's new Phoenix location went live on the map last week. New locations have a 60-day window where Google heavily weights early signals, and almost nobody works it deliberately. We got Verde's competitor 38 direction-requests/week in that window. Can I send the 4-step checklist?",
        by: "Mechanism: timing. New listings are the warmest cold audience that exists.",
      },
      { t: "h2", text: "4. The one-question email" },
      {
        t: "quote",
        text: "Subject: quick question about River Bend Fitness · Hi Sam — when a member cancels at River Bend, do you find out why before or after they're gone? Asking because we build the 48-hour win-back automation three Austin gyms use to recover 1 in 4 cancellations. One-line answer is plenty — I'll tell you exactly how we'd approach yours either way.",
        by: "Mechanism: radical brevity + a question that's easy and slightly intriguing to answer.",
      },
      { t: "h2", text: "5. The neighbor proof" },
      {
        t: "quote",
        text: "Subject: how Oak & Ivy booked out Saturdays · Hi Jess — Oak & Ivy (salon, ~1.2 mi from you) went from 60% to 97% Saturday occupancy in 8 weeks. Nothing exotic: review-triggered offers sent the week regulars went quiet. We mapped your regulars' review cadence and found the same pattern. Five minutes to show you the three \"about to churn\" segments?",
        by: "Mechanism: hyper-local social proof. National case studies feel irrelevant; the salon nearby doesn't.",
      },
      { t: "h2", text: "6. The honest audit" },
      {
        t: "quote",
        text: "Subject: 3 things on Summit's site that cost you calls · Hi Josh — ran Summit Exteriors through our 47-point local audit while researching Fort Collins roofers. Three quick items stood out — including a review-response pattern that's quietly hurting your map ranking. Two are 15-minute fixes. Want the PDF? (No call required, it's honestly more useful as a PDF.)",
        by: "Mechanism: give-first value with the pressure explicitly removed. \"No call required\" earns the call.",
      },
      { t: "h2", text: "7. The recruiter's early-bird" },
      {
        t: "quote",
        text: "Subject: congrats on the second clinic, Dr. Okafor · Hi Dr. Okafor — noticed Clearview opened its second Columbus location in January; expansion usually means you're about to fight for hygienists in a market where they're gone in 9 days. We placed 4 hygienists within 20 miles of your new location last quarter. Should I send their availability windows?",
        by: "Mechanism: signal-based timing (expansion = hiring) plus immediately useful inventory.",
      },
      { t: "h2", text: "8. The boring-industry wedge" },
      {
        t: "quote",
        text: "Subject: waste-hauling leads, no glamor involved · Hi Pete — let's skip the part where I pretend dumpster rentals are exciting. What is exciting: 41 contractors searched for roll-off service in your county last month, and Trevino Waste got 11 of them by being first to reply with a price. We built Trevino's instant-quote system. Want me to show you the workflow on a 9-minute call?",
        by: "Mechanism: voice-match. Plain talk for plain-spoken industries converts 2–3× better than marketing speak.",
      },
      { t: "h2", text: "9. The breakup (follow-up #3)" },
      {
        t: "quote",
        text: "Subject: closing the file on Brightline Pools · Hi Ana — I've sent two notes about the map audit for Brightline; going to stop here so I'm not that person in your inbox. Final thought: your rating (4.7★, 164 reviews) is the best asset your business owns, and one line of automation would triple how often happy customers add to it. If timing was just wrong, reply with \"later\" and I'll check back in Q3. Either way — good luck this season.",
        by: "Mechanism: respectful exit + an easy \"later\" escape hatch. Breakups earn 25–30% of total campaign replies.",
      },
      { t: "h2", text: "The follow-up math nobody wants to hear" },
      {
        t: "p",
        text: "Sending one email is asking once. The data across zybble campaigns is unambiguous: roughly 40% of positive replies come from the opener, 35% from follow-up one (day 2–3, new information, shorter), and 25% from the breakup (day 6–8). Anything beyond three touches is reputation destruction disguised as persistence. Vary the angle, shorten the email, and add new information — never send \"just bumping this to the top of your inbox,\" an opening line that has booked zero meetings in recorded history.",
      },
      {
        t: "list",
        items: [
          "Opener: specific observation + one low-friction ask (templates 1–6).",
          "Follow-up 1: a quick win or fresh proof, half the length (templates 7–8 style).",
          "Follow-up 2 / breakup: graceful exit with a \"later\" option (template 9).",
          "Full stop. Suppress the contact and revisit in 90 days with a new angle.",
        ],
      },
      {
        t: "callout",
        title: "The template paradox",
        text: "Templates scale structure, not sentences. The moment 500 businesses receive the identical \"I went through your reviews\" line, it's the new spam. Use these as skeletons — then let per-business data (rating, reviews, openings, competitors) fill in the flesh. That's exactly what zybble's AI Assistant does across thousands of leads per campaign.",
      },
      {
        t: "p",
        text: "Every template here starts the same way: with something true and specific about the recipient's business, pulled straight from the map. That specificity is why Google Maps leads outperform every other list source for local outreach — you're not guessing relevance, you're reading it. Get the list, verify the contacts, fill the skeletons with real observations, and send like a neighbor rather than a billboard. The replies take care of themselves.",
      },
    ],
  },
];

export function getPost(slug: string) {
  return POSTS.find((p) => p.slug === slug);
}
